export enum NotificationType {
  // ── Platform (email) ──────────────────────────
  WELCOME = 'WELCOME',
  PASSWORD_RESET = 'PASSWORD_RESET',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',

  // ── DMS (in-app) ─────────────────────────────
  CONNECTION_UNHEALTHY = 'CONNECTION_UNHEALTHY',
  MIGRATION_COMPLETE = 'MIGRATION_COMPLETE',
  QUOTA_WARNING = 'QUOTA_WARNING',
  CREDENTIAL_EXPIRING = 'CREDENTIAL_EXPIRING',
  PULL_COMPLETE = 'PULL_COMPLETE',
  PULL_FAILED = 'PULL_FAILED',
  OBJECT_LINK_COMPLETE = 'OBJECT_LINK_COMPLETE',
  COMMENT_ADDED = 'COMMENT_ADDED',
  ANNOTATION_ADDED = 'ANNOTATION_ADDED',
  AI_PROCESSING_COMPLETE = 'AI_PROCESSING_COMPLETE',
  AI_PROCESSING_FAILED = 'AI_PROCESSING_FAILED',
}
