-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "AUDIT_LOG_STATUS" AS ENUM ('SUCCESS', 'FAILURE', 'PARTIAL');

-- CreateTable
CREATE TABLE "AUDIT_LOGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "ACTION" TEXT NOT NULL,
    "RESOURCE" TEXT NOT NULL,
    "RESOURCE_ID" TEXT,
    "STATUS" "AUDIT_LOG_STATUS" NOT NULL DEFAULT 'SUCCESS',
    "IP_ADDRESS" TEXT,
    "USER_AGENT" TEXT,
    "DURATION" INTEGER,
    "SOURCE" TEXT,
    "TIMESTAMP" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AUDIT_LOGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "AUDIT_LOG_DETAILS" (
    "AUDIT_LOG_ID" INTEGER NOT NULL,
    "OLD_VALUE" JSONB,
    "NEW_VALUE" JSONB,
    "METADATA" JSONB,

    CONSTRAINT "AUDIT_LOG_DETAILS_pkey" PRIMARY KEY ("AUDIT_LOG_ID")
);

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_TENANT_ID_idx" ON "AUDIT_LOGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_TENANT_ID_USER_ID_idx" ON "AUDIT_LOGS"("TENANT_ID", "USER_ID");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_TENANT_ID_TIMESTAMP_idx" ON "AUDIT_LOGS"("TENANT_ID", "TIMESTAMP");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_USER_ID_idx" ON "AUDIT_LOGS"("USER_ID");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_RESOURCE_RESOURCE_ID_idx" ON "AUDIT_LOGS"("RESOURCE", "RESOURCE_ID");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_ACTION_idx" ON "AUDIT_LOGS"("ACTION");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_TIMESTAMP_idx" ON "AUDIT_LOGS"("TIMESTAMP");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_USER_ID_TIMESTAMP_idx" ON "AUDIT_LOGS"("USER_ID", "TIMESTAMP");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_STATUS_idx" ON "AUDIT_LOGS"("STATUS");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_ACTION_TIMESTAMP_idx" ON "AUDIT_LOGS"("ACTION", "TIMESTAMP");

-- CreateIndex
CREATE INDEX "AUDIT_LOGS_IP_ADDRESS_idx" ON "AUDIT_LOGS"("IP_ADDRESS");

-- AddForeignKey
ALTER TABLE "AUDIT_LOG_DETAILS" ADD CONSTRAINT "AUDIT_LOG_DETAILS_AUDIT_LOG_ID_fkey" FOREIGN KEY ("AUDIT_LOG_ID") REFERENCES "AUDIT_LOGS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
