-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "AUTH_TYPE" AS ENUM ('PASSWORD', 'SSO_GOOGLE', 'SSO_MICROSOFT', 'SAML', 'MAGIC_LINK', 'LDAP');

-- CreateEnum
CREATE TYPE "SSO_PROVIDER_TYPE" AS ENUM ('GOOGLE', 'MICROSOFT', 'SAML', 'OKTA', 'LDAP', 'CUSTOM');

-- CreateEnum
CREATE TYPE "MFA_TYPE" AS ENUM ('EMAIL_OTP', 'SMS_OTP', 'AUTHENTICATOR_APP');

-- CreateEnum
CREATE TYPE "LOGIN_ATTEMPT_STATUS" AS ENUM ('SUCCESS', 'FAILED', 'BLOCKED');

-- CreateEnum
CREATE TYPE "TOKEN_STATUS" AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "CREDENTIAL_STATUS" AS ENUM ('ACTIVE', 'INACTIVE', 'LOCKED');

-- CreateEnum
CREATE TYPE "AUTH_GENERIC_STATUS" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateTable
CREATE TABLE "TENANT_AUTH_CONFIGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "IS_MFA_MANDATORY" BOOLEAN NOT NULL DEFAULT false,
    "ALLOWED_AUTH_TYPES" JSONB NOT NULL DEFAULT '["PASSWORD"]',
    "PASSWORD_MIN_LENGTH" INTEGER NOT NULL DEFAULT 8,
    "PASSWORD_REQUIRE_UPPERCASE" BOOLEAN NOT NULL DEFAULT true,
    "PASSWORD_REQUIRE_NUMBER" BOOLEAN NOT NULL DEFAULT true,
    "PASSWORD_REQUIRE_SPECIAL_CHAR" BOOLEAN NOT NULL DEFAULT true,
    "PASSWORD_HISTORY_COUNT" INTEGER NOT NULL DEFAULT 3,
    "MAX_FAILED_ATTEMPTS" INTEGER NOT NULL DEFAULT 5,
    "LOCKOUT_DURATION_MINUTES" INTEGER NOT NULL DEFAULT 30,
    "SESSION_TIMEOUT_MINUTES" INTEGER NOT NULL DEFAULT 60,
    "MAX_CONCURRENT_SESSIONS" INTEGER NOT NULL DEFAULT 5,
    "REFRESH_TOKEN_VALIDITY_DAYS" INTEGER NOT NULL DEFAULT 7,
    "IS_LDAP_SYNC_ENABLED" BOOLEAN NOT NULL DEFAULT false,
    "LDAP_SYNC_FREQUENCY" TEXT,
    "LDAP_LAST_SYNCED_AT" TIMESTAMP(3),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_AUTH_CONFIGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "SSO_PROVIDER_CONFIGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "PROVIDER_TYPE" "SSO_PROVIDER_TYPE" NOT NULL,
    "CLIENT_ID" TEXT NOT NULL,
    "CLIENT_SECRET" TEXT NOT NULL,
    "REDIRECT_URL" TEXT,
    "METADATA_URL" TEXT,
    "LDAP_HOST" TEXT,
    "LDAP_BASE_DN" TEXT,
    "LDAP_BIND_USER" TEXT,
    "LDAP_BIND_PASSWORD" TEXT,
    "STATUS" "AUTH_GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SSO_PROVIDER_CONFIGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "USER_CREDENTIALS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "AUTH_TYPE" "AUTH_TYPE" NOT NULL,
    "PASSWORD_HASH" TEXT,
    "SSO_PROVIDER_ID" INTEGER,
    "STATUS" "CREDENTIAL_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_CREDENTIALS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PASSWORD_HISTORY" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "PASSWORD_HASH" TEXT NOT NULL,
    "CHANGED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PASSWORD_HISTORY_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "REFRESH_TOKENS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "TOKEN_HASH" TEXT NOT NULL,
    "DEVICE_INFO" TEXT,
    "IP_ADDRESS" TEXT,
    "ISSUED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "STATUS" "TOKEN_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "MFA_CONFIGS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "MFA_TYPE" "MFA_TYPE" NOT NULL,
    "SECRET_KEY" TEXT,
    "PHONE_NUMBER" TEXT,
    "IS_VERIFIED" BOOLEAN NOT NULL DEFAULT false,
    "STATUS" "AUTH_GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MFA_CONFIGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "LOGIN_ATTEMPTS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER,
    "TENANT_ID" INTEGER NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "IP_ADDRESS" TEXT,
    "DEVICE_INFO" TEXT,
    "LOCATION" TEXT,
    "ATTEMPT_TYPE" "AUTH_TYPE" NOT NULL,
    "STATUS" "LOGIN_ATTEMPT_STATUS" NOT NULL,
    "FAILURE_REASON" TEXT,
    "ATTEMPTED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "LOGIN_ATTEMPTS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TENANT_AUTH_CONFIGS_TENANT_ID_key" ON "TENANT_AUTH_CONFIGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "SSO_PROVIDER_CONFIGS_TENANT_ID_idx" ON "SSO_PROVIDER_CONFIGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "SSO_PROVIDER_CONFIGS_TENANT_ID_PROVIDER_TYPE_idx" ON "SSO_PROVIDER_CONFIGS"("TENANT_ID", "PROVIDER_TYPE");

-- CreateIndex
CREATE UNIQUE INDEX "USER_CREDENTIALS_USER_ID_key" ON "USER_CREDENTIALS"("USER_ID");

-- CreateIndex
CREATE INDEX "USER_CREDENTIALS_TENANT_ID_idx" ON "USER_CREDENTIALS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "USER_CREDENTIALS_SSO_PROVIDER_ID_idx" ON "USER_CREDENTIALS"("SSO_PROVIDER_ID");

-- CreateIndex
CREATE INDEX "USER_CREDENTIALS_TENANT_ID_STATUS_idx" ON "USER_CREDENTIALS"("TENANT_ID", "STATUS");

-- CreateIndex
CREATE INDEX "PASSWORD_HISTORY_USER_ID_idx" ON "PASSWORD_HISTORY"("USER_ID");

-- CreateIndex
CREATE INDEX "PASSWORD_HISTORY_USER_ID_CHANGED_AT_idx" ON "PASSWORD_HISTORY"("USER_ID", "CHANGED_AT");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_USER_ID_idx" ON "REFRESH_TOKENS"("USER_ID");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_TENANT_ID_idx" ON "REFRESH_TOKENS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_TOKEN_HASH_idx" ON "REFRESH_TOKENS"("TOKEN_HASH");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_STATUS_idx" ON "REFRESH_TOKENS"("STATUS");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_USER_ID_STATUS_idx" ON "REFRESH_TOKENS"("USER_ID", "STATUS");

-- CreateIndex
CREATE INDEX "REFRESH_TOKENS_EXPIRES_AT_idx" ON "REFRESH_TOKENS"("EXPIRES_AT");

-- CreateIndex
CREATE UNIQUE INDEX "MFA_CONFIGS_USER_ID_key" ON "MFA_CONFIGS"("USER_ID");

-- CreateIndex
CREATE INDEX "MFA_CONFIGS_TENANT_ID_idx" ON "MFA_CONFIGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_USER_ID_idx" ON "LOGIN_ATTEMPTS"("USER_ID");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_TENANT_ID_idx" ON "LOGIN_ATTEMPTS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_EMAIL_idx" ON "LOGIN_ATTEMPTS"("EMAIL");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_TENANT_ID_EMAIL_ATTEMPTED_AT_idx" ON "LOGIN_ATTEMPTS"("TENANT_ID", "EMAIL", "ATTEMPTED_AT");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_IP_ADDRESS_idx" ON "LOGIN_ATTEMPTS"("IP_ADDRESS");

-- CreateIndex
CREATE INDEX "LOGIN_ATTEMPTS_ATTEMPTED_AT_idx" ON "LOGIN_ATTEMPTS"("ATTEMPTED_AT");

-- AddForeignKey
ALTER TABLE "USER_CREDENTIALS" ADD CONSTRAINT "USER_CREDENTIALS_SSO_PROVIDER_ID_fkey" FOREIGN KEY ("SSO_PROVIDER_ID") REFERENCES "SSO_PROVIDER_CONFIGS"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PASSWORD_HISTORY" ADD CONSTRAINT "PASSWORD_HISTORY_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USER_CREDENTIALS"("USER_ID") ON DELETE CASCADE ON UPDATE CASCADE;
