-- CreateTable
CREATE TABLE IF NOT EXISTS "TENANT_LICENSE" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "PLAN_ID" INTEGER NOT NULL,
    "CYCLE" TEXT NOT NULL,
    "MAX_USERS" INTEGER,
    "START_DATE" TIMESTAMP(3) NOT NULL,
    "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "ISSUED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "SIGNATURE_HASH" TEXT NOT NULL,
    "LICENSE_DATA" JSONB NOT NULL,
    "ISSUED_BY" INTEGER NOT NULL,
    "STATUS" TEXT NOT NULL DEFAULT 'ACTIVE',
    "VERSION" INTEGER NOT NULL DEFAULT 1,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_LICENSE_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "TENANT_LICENSE_TENANT_ID_idx" ON "TENANT_LICENSE"("TENANT_ID");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "TENANT_LICENSE_TENANT_ID_STATUS_idx" ON "TENANT_LICENSE"("TENANT_ID", "STATUS");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "TENANT_LICENSE_TENANT_ID_VERSION_idx" ON "TENANT_LICENSE"("TENANT_ID", "VERSION");

-- AddForeignKey
ALTER TABLE "TENANT_LICENSE" ADD CONSTRAINT "TENANT_LICENSE_PLAN_ID_fkey"
    FOREIGN KEY ("PLAN_ID") REFERENCES "PLAN"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
