-- CreateEnum
CREATE TYPE "NOTIFICATION_TYPE" AS ENUM ('WELCOME', 'PASSWORD_RESET', 'PASSWORD_CHANGED');

-- CreateTable
CREATE TABLE "TENANT_BRANDINGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "COMPANY_NAME" TEXT NOT NULL,
    "LOGO_URL" TEXT,
    "PRIMARY_COLOR" TEXT NOT NULL DEFAULT '#18181b',
    "SECONDARY_COLOR" TEXT,
    "FOOTER_TEXT" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_BRANDINGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "EMAIL_TEMPLATES" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "TYPE" "NOTIFICATION_TYPE" NOT NULL,
    "SUBJECT" TEXT NOT NULL,
    "HTML_BODY" TEXT NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EMAIL_TEMPLATES_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "TENANT_BRANDINGS_TENANT_ID_key" ON "TENANT_BRANDINGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "TENANT_BRANDINGS_TENANT_ID_idx" ON "TENANT_BRANDINGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "EMAIL_TEMPLATES_TENANT_ID_idx" ON "EMAIL_TEMPLATES"("TENANT_ID");

-- CreateIndex
CREATE INDEX "EMAIL_TEMPLATES_TENANT_ID_TYPE_idx" ON "EMAIL_TEMPLATES"("TENANT_ID", "TYPE");

-- CreateIndex
CREATE UNIQUE INDEX "EMAIL_TEMPLATES_TENANT_ID_TYPE_key" ON "EMAIL_TEMPLATES"("TENANT_ID", "TYPE");
