-- AlterTable: add on-prem related columns to TENANTS
ALTER TABLE "TENANTS" ADD COLUMN "IS_ON_PREM" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TENANTS" ADD COLUMN "LICENSE_EXPIRY_DATE" DATE;

-- CreateIndex
CREATE INDEX "TENANTS_IS_ON_PREM_idx" ON "TENANTS"("IS_ON_PREM");
