-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "FEATURE_STATUS" AS ENUM ('ACTIVE', 'INACTIVE', 'DEPRECATED');

-- CreateEnum
CREATE TYPE "LICENSE_GENERIC_STATUS" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateEnum
CREATE TYPE "LICENSE_BILLING_CYCLE" AS ENUM ('MONTHLY', 'ANNUALLY');

-- CreateEnum
CREATE TYPE "TOP_UP_STATUS" AS ENUM ('ACTIVE', 'EXPIRED', 'FULLY_CONSUMED');

-- CreateTable
CREATE TABLE "FEATURE_REGISTRY" (
    "ID" SERIAL NOT NULL,
    "FEATURE_KEY" TEXT NOT NULL,
    "FEATURE_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    -- Arc dependency graph: feature keys this one depends on. Empty = root.
    "DEPENDS_ON" TEXT[] NOT NULL DEFAULT '{}',
    "STATUS" "FEATURE_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FEATURE_REGISTRY_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PLAN" (
    "ID" SERIAL NOT NULL,
    "PLAN_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" "LICENSE_GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PLAN_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PLAN_FEATURE_QUOTA" (
    "PLAN_ID" INTEGER NOT NULL,
    "FEATURE_ID" INTEGER NOT NULL,
    "QUOTA_LIMIT" INTEGER,
    "IS_ENABLED" BOOLEAN NOT NULL DEFAULT true,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PLAN_FEATURE_QUOTA_pkey" PRIMARY KEY ("PLAN_ID","FEATURE_ID")
);

-- CreateTable
CREATE TABLE "PLAN_PRICING" (
    "ID" SERIAL NOT NULL,
    "PLAN_ID" INTEGER NOT NULL,
    "BILLING_CYCLE" "LICENSE_BILLING_CYCLE" NOT NULL,
    "PRICE" DECIMAL(12,2) NOT NULL,
    "CURRENCY" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "STATUS" "LICENSE_GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PLAN_PRICING_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TOP_UP_PRICING" (
    "ID" SERIAL NOT NULL,
    "FEATURE_ID" INTEGER NOT NULL,
    "QUOTA_AMOUNT" INTEGER NOT NULL,
    "PRICE" DECIMAL(12,2) NOT NULL,
    "CURRENCY" VARCHAR(3) NOT NULL DEFAULT 'USD',
    "VALIDITY_DAYS" INTEGER NOT NULL,
    "STATUS" "LICENSE_GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TOP_UP_PRICING_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "QUOTA_TOP_UP" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "FEATURE_ID" INTEGER NOT NULL,
    "ADDITIONAL_QUOTA" INTEGER NOT NULL,
    "CONSUMED" INTEGER NOT NULL DEFAULT 0,
    "PURCHASED_DATE" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EXPIRY_DATE" TIMESTAMP(3) NOT NULL,
    "STATUS" "TOP_UP_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "QUOTA_TOP_UP_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "USAGE_LEDGER" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "FEATURE_ID" INTEGER NOT NULL,
    "USER_ID" INTEGER,
    "CONSUMED" INTEGER NOT NULL DEFAULT 0,
    "CYCLE_START_DATE" TIMESTAMP(3) NOT NULL,
    "CYCLE_END_DATE" TIMESTAMP(3) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USAGE_LEDGER_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "FEATURE_REGISTRY_FEATURE_KEY_key" ON "FEATURE_REGISTRY"("FEATURE_KEY");

-- CreateIndex
CREATE INDEX "FEATURE_REGISTRY_STATUS_idx" ON "FEATURE_REGISTRY"("STATUS");

-- CreateIndex
CREATE UNIQUE INDEX "PLAN_PLAN_NAME_key" ON "PLAN"("PLAN_NAME");

-- CreateIndex
CREATE INDEX "PLAN_STATUS_idx" ON "PLAN"("STATUS");

-- CreateIndex
CREATE INDEX "PLAN_FEATURE_QUOTA_FEATURE_ID_idx" ON "PLAN_FEATURE_QUOTA"("FEATURE_ID");

-- CreateIndex
CREATE INDEX "PLAN_PRICING_PLAN_ID_idx" ON "PLAN_PRICING"("PLAN_ID");

-- CreateIndex
CREATE INDEX "PLAN_PRICING_STATUS_idx" ON "PLAN_PRICING"("STATUS");

-- CreateIndex
CREATE UNIQUE INDEX "PLAN_PRICING_PLAN_ID_BILLING_CYCLE_CURRENCY_key" ON "PLAN_PRICING"("PLAN_ID", "BILLING_CYCLE", "CURRENCY");

-- CreateIndex
CREATE INDEX "TOP_UP_PRICING_FEATURE_ID_idx" ON "TOP_UP_PRICING"("FEATURE_ID");

-- CreateIndex
CREATE INDEX "TOP_UP_PRICING_STATUS_idx" ON "TOP_UP_PRICING"("STATUS");

-- CreateIndex
CREATE INDEX "QUOTA_TOP_UP_TENANT_ID_FEATURE_ID_idx" ON "QUOTA_TOP_UP"("TENANT_ID", "FEATURE_ID");

-- CreateIndex
CREATE INDEX "QUOTA_TOP_UP_TENANT_ID_FEATURE_ID_STATUS_idx" ON "QUOTA_TOP_UP"("TENANT_ID", "FEATURE_ID", "STATUS");

-- CreateIndex
CREATE INDEX "QUOTA_TOP_UP_TENANT_ID_STATUS_idx" ON "QUOTA_TOP_UP"("TENANT_ID", "STATUS");

-- CreateIndex
CREATE INDEX "QUOTA_TOP_UP_EXPIRY_DATE_idx" ON "QUOTA_TOP_UP"("EXPIRY_DATE");

-- CreateIndex
CREATE INDEX "USAGE_LEDGER_TENANT_ID_FEATURE_ID_CYCLE_START_DATE_idx" ON "USAGE_LEDGER"("TENANT_ID", "FEATURE_ID", "CYCLE_START_DATE");

-- CreateIndex
CREATE INDEX "USAGE_LEDGER_TENANT_ID_idx" ON "USAGE_LEDGER"("TENANT_ID");

-- CreateIndex
CREATE INDEX "USAGE_LEDGER_FEATURE_ID_idx" ON "USAGE_LEDGER"("FEATURE_ID");

-- AddForeignKey
ALTER TABLE "PLAN_FEATURE_QUOTA" ADD CONSTRAINT "PLAN_FEATURE_QUOTA_PLAN_ID_fkey" FOREIGN KEY ("PLAN_ID") REFERENCES "PLAN"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLAN_FEATURE_QUOTA" ADD CONSTRAINT "PLAN_FEATURE_QUOTA_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "FEATURE_REGISTRY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PLAN_PRICING" ADD CONSTRAINT "PLAN_PRICING_PLAN_ID_fkey" FOREIGN KEY ("PLAN_ID") REFERENCES "PLAN"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TOP_UP_PRICING" ADD CONSTRAINT "TOP_UP_PRICING_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "FEATURE_REGISTRY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QUOTA_TOP_UP" ADD CONSTRAINT "QUOTA_TOP_UP_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "FEATURE_REGISTRY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USAGE_LEDGER" ADD CONSTRAINT "USAGE_LEDGER_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "FEATURE_REGISTRY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
