export const AUTH_SERVICE = 'AUTH_SERVICE';
export const AUDIT_SERVICE = 'AUDIT_SERVICE';
export const TENANT_SERVICE = 'TENANT_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const LICENSE_SERVICE = 'LICENSE_SERVICE';
export const ADMIN_PORTAL = 'ADMIN_PORTAL';

export const AUTH_SERVICE_PORT = 5001;
export const AUDIT_SERVICE_PORT = 5002;
export const TENANT_SERVICE_PORT = 5003;
export const USERS_SERVICE_PORT = 5004;
export const LICENSE_SERVICE_PORT = 5005;
export const ADMIN_PORTAL_PORT = 5006;

export const AUTH_SERVICE_HTTP_PORT = 6001;
export const AUDIT_SERVICE_HTTP_PORT = 6002;
export const TENANT_SERVICE_HTTP_PORT = 6003;
export const USERS_SERVICE_HTTP_PORT = 6004;
export const LICENSE_SERVICE_HTTP_PORT = 6005;
export const ADMIN_PORTAL_HTTP_PORT = 6006;

export const SYSTEM_TENANT_ID = 0;
