-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "TENANT_STATUS" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "QUOTA_TYPE" AS ENUM ('SHARED', 'INDIVIDUAL');

-- CreateEnum
CREATE TYPE "BILLING_CYCLE" AS ENUM ('MONTHLY', 'ANNUALLY');

-- CreateEnum
CREATE TYPE "BILLING_TYPE" AS ENUM ('PLAN_SUBSCRIPTION', 'TOP_UP');

-- CreateEnum
CREATE TYPE "PAYMENT_STATUS" AS ENUM ('PENDING', 'PAID', 'FAILED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "PAYMENT_METHOD" AS ENUM ('CARD', 'BANK', 'UPI');

-- CreateEnum
CREATE TYPE "INVOICE_STATUS" AS ENUM ('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED');

-- CreateEnum
CREATE TYPE "PLAN_CHANGE_TYPE" AS ENUM ('INITIAL', 'UPGRADE', 'DOWNGRADE');

-- CreateTable
CREATE TABLE "TENANTS" (
    "ID" SERIAL NOT NULL,
    "PLAN_ID" TEXT NOT NULL,
    "NEXT_PLAN_ID" TEXT,
    "QUOTA_TYPE" "QUOTA_TYPE" NOT NULL,
    "MAX_USERS" INTEGER,
    "BILLING_CYCLE" "BILLING_CYCLE",
    "CYCLE_START_DATE" DATE,
    "TENANT_NAME" TEXT NOT NULL,
    "DOMAIN" TEXT NOT NULL,
    "STATUS" "TENANT_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANTS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TENANT_PLAN_HISTORY" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "PLAN_ID" TEXT NOT NULL,
    "CHANGE_TYPE" "PLAN_CHANGE_TYPE" NOT NULL,
    "START_DATE" DATE NOT NULL,
    "END_DATE" DATE,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TENANT_PLAN_HISTORY_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "TENANT_BILLINGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "BILLING_TYPE" "BILLING_TYPE" NOT NULL,
    "REFERENCE_ID" TEXT NOT NULL,
    "AMOUNT" DECIMAL(12,2) NOT NULL,
    "CURRENCY" TEXT NOT NULL DEFAULT 'USD',
    "BILLING_DATE" DATE NOT NULL,
    "NEXT_BILLING_DATE" DATE,
    "PAYMENT_STATUS" "PAYMENT_STATUS" NOT NULL DEFAULT 'PENDING',
    "PAYMENT_METHOD" "PAYMENT_METHOD" NOT NULL,
    "TRANSACTION_ID" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_BILLINGS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "INVOICES" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "BILLING_ID" INTEGER NOT NULL,
    "INVOICE_NUMBER" TEXT NOT NULL,
    "AMOUNT" DECIMAL(12,2) NOT NULL,
    "CURRENCY" TEXT NOT NULL DEFAULT 'USD',
    "TAX_AMOUNT" DECIMAL(12,2) NOT NULL,
    "TOTAL_AMOUNT" DECIMAL(12,2) NOT NULL,
    "INVOICE_DATE" DATE NOT NULL,
    "DUE_DATE" DATE NOT NULL,
    "STATUS" "INVOICE_STATUS" NOT NULL DEFAULT 'DRAFT',
    "PDF_URL" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "INVOICES_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "TENANTS_STATUS_idx" ON "TENANTS"("STATUS");

-- CreateIndex
CREATE INDEX "TENANTS_DOMAIN_idx" ON "TENANTS"("DOMAIN");

-- CreateIndex
CREATE INDEX "TENANTS_PLAN_ID_idx" ON "TENANTS"("PLAN_ID");

-- CreateIndex
CREATE INDEX "TENANT_PLAN_HISTORY_TENANT_ID_idx" ON "TENANT_PLAN_HISTORY"("TENANT_ID");

-- CreateIndex
CREATE INDEX "TENANT_PLAN_HISTORY_TENANT_ID_START_DATE_idx" ON "TENANT_PLAN_HISTORY"("TENANT_ID", "START_DATE");

-- CreateIndex
CREATE INDEX "TENANT_BILLINGS_TENANT_ID_idx" ON "TENANT_BILLINGS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "TENANT_BILLINGS_PAYMENT_STATUS_idx" ON "TENANT_BILLINGS"("PAYMENT_STATUS");

-- CreateIndex
CREATE INDEX "TENANT_BILLINGS_TENANT_ID_PAYMENT_STATUS_idx" ON "TENANT_BILLINGS"("TENANT_ID", "PAYMENT_STATUS");

-- CreateIndex
CREATE INDEX "TENANT_BILLINGS_NEXT_BILLING_DATE_idx" ON "TENANT_BILLINGS"("NEXT_BILLING_DATE");

-- CreateIndex
CREATE UNIQUE INDEX "INVOICES_BILLING_ID_key" ON "INVOICES"("BILLING_ID");

-- CreateIndex
CREATE UNIQUE INDEX "INVOICES_INVOICE_NUMBER_key" ON "INVOICES"("INVOICE_NUMBER");

-- CreateIndex
CREATE INDEX "INVOICES_TENANT_ID_idx" ON "INVOICES"("TENANT_ID");

-- CreateIndex
CREATE INDEX "INVOICES_INVOICE_NUMBER_idx" ON "INVOICES"("INVOICE_NUMBER");

-- CreateIndex
CREATE INDEX "INVOICES_TENANT_ID_STATUS_idx" ON "INVOICES"("TENANT_ID", "STATUS");

-- CreateIndex
CREATE INDEX "INVOICES_DUE_DATE_idx" ON "INVOICES"("DUE_DATE");

-- AddForeignKey
ALTER TABLE "TENANT_PLAN_HISTORY" ADD CONSTRAINT "TENANT_PLAN_HISTORY_TENANT_ID_fkey" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TENANT_BILLINGS" ADD CONSTRAINT "TENANT_BILLINGS_TENANT_ID_fkey" FOREIGN KEY ("TENANT_ID") REFERENCES "TENANTS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "INVOICES" ADD CONSTRAINT "INVOICES_BILLING_ID_fkey" FOREIGN KEY ("BILLING_ID") REFERENCES "TENANT_BILLINGS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
