/*
  Warnings:

  - The `STATUS` column on the `TENANT_LICENSE` table would be dropped and recreated. This will lead to data loss if there is data in the column.
  - Changed the type of `CYCLE` on the `TENANT_LICENSE` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "LICENSE_STATUS" AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');

-- AlterTable
ALTER TABLE "FEATURE_REGISTRY" ADD COLUMN     "CATEGORY" TEXT,
ADD COLUMN     "VALUE_TYPE" TEXT NOT NULL DEFAULT 'boolean';

-- AlterTable
ALTER TABLE "TENANT_LICENSE" DROP COLUMN "CYCLE",
ADD COLUMN     "CYCLE" "LICENSE_BILLING_CYCLE" NOT NULL,
DROP COLUMN "STATUS",
ADD COLUMN     "STATUS" "LICENSE_STATUS" NOT NULL DEFAULT 'ACTIVE';

-- CreateTable
CREATE TABLE "TENANT_FEATURE_CONFIG" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "FEATURE_ID" INTEGER NOT NULL,
    "CONFIG_VALUE" TEXT,
    "IS_ENABLED" BOOLEAN NOT NULL DEFAULT true,
    "SET_BY" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TENANT_FEATURE_CONFIG_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "TENANT_FEATURE_CONFIG_TENANT_ID_idx" ON "TENANT_FEATURE_CONFIG"("TENANT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "TENANT_FEATURE_CONFIG_TENANT_ID_FEATURE_ID_key" ON "TENANT_FEATURE_CONFIG"("TENANT_ID", "FEATURE_ID");

-- CreateIndex
CREATE INDEX "FEATURE_REGISTRY_CATEGORY_idx" ON "FEATURE_REGISTRY"("CATEGORY");

-- CreateIndex
CREATE INDEX "TENANT_LICENSE_TENANT_ID_STATUS_idx" ON "TENANT_LICENSE"("TENANT_ID", "STATUS");

-- AddForeignKey
ALTER TABLE "TENANT_FEATURE_CONFIG" ADD CONSTRAINT "TENANT_FEATURE_CONFIG_FEATURE_ID_fkey" FOREIGN KEY ("FEATURE_ID") REFERENCES "FEATURE_REGISTRY"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
