-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "USER_STATUS" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "GENERIC_STATUS" AS ENUM ('ACTIVE', 'INACTIVE');

-- CreateTable
CREATE TABLE "MODULE_MASTER" (
    "ID" SERIAL NOT NULL,
    "MODULE_NAME" TEXT NOT NULL,
    "MODULE_KEY" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    -- Arc dependency graph: keys of modules this one depends on. Empty = root.
    "DEPENDS_ON" TEXT[] NOT NULL DEFAULT '{}',
    "STATUS" "GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MODULE_MASTER_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PERMISSION_MASTER" (
    "ID" SERIAL NOT NULL,
    "PERMISSION_NAME" TEXT NOT NULL,
    "PERMISSION_KEY" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" "GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PERMISSION_MASTER_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "MODULE_PERMISSIONS" (
    "MODULE_ID" INTEGER NOT NULL,
    "PERMISSION_ID" INTEGER NOT NULL,
    "STATUS" "GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT "MODULE_PERMISSIONS_pkey" PRIMARY KEY ("MODULE_ID","PERMISSION_ID")
);

-- CreateTable
CREATE TABLE "ROLES" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "ROLE_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" "GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ROLES_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ROLE_MODULE_PERMISSIONS" (
    "ROLE_ID" INTEGER NOT NULL,
    "MODULE_ID" INTEGER NOT NULL,
    "PERMISSION_ID" INTEGER NOT NULL,
    "IS_ENABLED" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "ROLE_MODULE_PERMISSIONS_pkey" PRIMARY KEY ("ROLE_ID","MODULE_ID","PERMISSION_ID")
);

-- CreateTable
CREATE TABLE "GROUPS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "GROUP_NAME" TEXT NOT NULL,
    "DESCRIPTION" TEXT,
    "STATUS" "GENERIC_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GROUPS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "GROUP_ROLES" (
    "GROUP_ID" INTEGER NOT NULL,
    "ROLE_ID" INTEGER NOT NULL,

    CONSTRAINT "GROUP_ROLES_pkey" PRIMARY KEY ("GROUP_ID","ROLE_ID")
);

-- CreateTable
CREATE TABLE "USERS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "PHONE" TEXT,
    "STATUS" "USER_STATUS" NOT NULL DEFAULT 'ACTIVE',
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "USER_ROLES" (
    "USER_ID" INTEGER NOT NULL,
    "ROLE_ID" INTEGER NOT NULL,

    CONSTRAINT "USER_ROLES_pkey" PRIMARY KEY ("USER_ID","ROLE_ID")
);

-- CreateTable
CREATE TABLE "USER_GROUPS" (
    "USER_ID" INTEGER NOT NULL,
    "GROUP_ID" INTEGER NOT NULL,

    CONSTRAINT "USER_GROUPS_pkey" PRIMARY KEY ("USER_ID","GROUP_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "MODULE_MASTER_MODULE_KEY_key" ON "MODULE_MASTER"("MODULE_KEY");

-- CreateIndex
CREATE UNIQUE INDEX "PERMISSION_MASTER_PERMISSION_KEY_key" ON "PERMISSION_MASTER"("PERMISSION_KEY");

-- CreateIndex
CREATE INDEX "MODULE_PERMISSIONS_PERMISSION_ID_idx" ON "MODULE_PERMISSIONS"("PERMISSION_ID");

-- CreateIndex
CREATE INDEX "ROLES_TENANT_ID_idx" ON "ROLES"("TENANT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "ROLES_TENANT_ID_ROLE_NAME_key" ON "ROLES"("TENANT_ID", "ROLE_NAME");

-- CreateIndex
CREATE INDEX "ROLE_MODULE_PERMISSIONS_MODULE_ID_PERMISSION_ID_idx" ON "ROLE_MODULE_PERMISSIONS"("MODULE_ID", "PERMISSION_ID");

-- CreateIndex
CREATE INDEX "GROUPS_TENANT_ID_idx" ON "GROUPS"("TENANT_ID");

-- CreateIndex
CREATE UNIQUE INDEX "GROUPS_TENANT_ID_GROUP_NAME_key" ON "GROUPS"("TENANT_ID", "GROUP_NAME");

-- CreateIndex
CREATE INDEX "GROUP_ROLES_ROLE_ID_idx" ON "GROUP_ROLES"("ROLE_ID");

-- CreateIndex
CREATE INDEX "USERS_TENANT_ID_idx" ON "USERS"("TENANT_ID");

-- CreateIndex
CREATE INDEX "USERS_EMAIL_idx" ON "USERS"("EMAIL");

-- CreateIndex
CREATE INDEX "USERS_TENANT_ID_STATUS_idx" ON "USERS"("TENANT_ID", "STATUS");

-- CreateIndex
CREATE UNIQUE INDEX "USERS_TENANT_ID_EMAIL_key" ON "USERS"("TENANT_ID", "EMAIL");

-- CreateIndex
CREATE INDEX "USER_ROLES_ROLE_ID_idx" ON "USER_ROLES"("ROLE_ID");

-- CreateIndex
CREATE INDEX "USER_GROUPS_GROUP_ID_idx" ON "USER_GROUPS"("GROUP_ID");

-- AddForeignKey
ALTER TABLE "MODULE_PERMISSIONS" ADD CONSTRAINT "MODULE_PERMISSIONS_MODULE_ID_fkey" FOREIGN KEY ("MODULE_ID") REFERENCES "MODULE_MASTER"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MODULE_PERMISSIONS" ADD CONSTRAINT "MODULE_PERMISSIONS_PERMISSION_ID_fkey" FOREIGN KEY ("PERMISSION_ID") REFERENCES "PERMISSION_MASTER"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLE_MODULE_PERMISSIONS" ADD CONSTRAINT "ROLE_MODULE_PERMISSIONS_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ROLE_MODULE_PERMISSIONS" ADD CONSTRAINT "ROLE_MODULE_PERMISSIONS_MODULE_ID_PERMISSION_ID_fkey" FOREIGN KEY ("MODULE_ID", "PERMISSION_ID") REFERENCES "MODULE_PERMISSIONS"("MODULE_ID", "PERMISSION_ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_GROUP_ID_fkey" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUPS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "GROUP_ROLES" ADD CONSTRAINT "GROUP_ROLES_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USERS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_ROLES" ADD CONSTRAINT "USER_ROLES_ROLE_ID_fkey" FOREIGN KEY ("ROLE_ID") REFERENCES "ROLES"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "USERS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_GROUPS" ADD CONSTRAINT "USER_GROUPS_GROUP_ID_fkey" FOREIGN KEY ("GROUP_ID") REFERENCES "GROUPS"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
