-- CreateTable
CREATE TABLE "PASSWORD_RESET_TOKENS" (
    "ID" SERIAL NOT NULL,
    "USER_ID" INTEGER NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "TOKEN_HASH" TEXT NOT NULL,
    "EXPIRES_AT" TIMESTAMP(3) NOT NULL,
    "USED_AT" TIMESTAMP(3),
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PASSWORD_RESET_TOKENS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE INDEX "PASSWORD_RESET_TOKENS_TOKEN_HASH_idx" ON "PASSWORD_RESET_TOKENS"("TOKEN_HASH");

-- CreateIndex
CREATE INDEX "PASSWORD_RESET_TOKENS_USER_ID_idx" ON "PASSWORD_RESET_TOKENS"("USER_ID");

-- CreateIndex
CREATE INDEX "PASSWORD_RESET_TOKENS_EXPIRES_AT_idx" ON "PASSWORD_RESET_TOKENS"("EXPIRES_AT");
