-- CreateEnum (idempotent — safe to re-run if already exists)
DO $$ BEGIN
  CREATE TYPE "NOTIFICATION_STATUS" AS ENUM ('SENT', 'FAILED', 'PENDING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "NOTIFICATION_TYPE" AS ENUM ('WELCOME', 'PASSWORD_RESET', 'PASSWORD_CHANGED', 'REPORT_DELIVERED', 'SCHEDULED_REPORT_FAILED', 'DASHBOARD_REFRESH_FAILED', 'ANOMALY_DETECTED', 'QUOTA_WARNING', 'CREDENTIAL_EXPIRING');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE "NOTIFICATION_CHANNEL" AS ENUM ('EMAIL');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- CreateTable (idempotent)
CREATE TABLE IF NOT EXISTS "NOTIFICATION_LOGS" (
    "ID" SERIAL NOT NULL,
    "TENANT_ID" INTEGER NOT NULL,
    "RECIPIENT_EMAIL" TEXT NOT NULL,
    "TYPE" "NOTIFICATION_TYPE" NOT NULL,
    "CHANNEL" "NOTIFICATION_CHANNEL" NOT NULL DEFAULT 'EMAIL',
    "SUBJECT" TEXT NOT NULL,
    "STATUS" "NOTIFICATION_STATUS" NOT NULL,
    "ERROR_MESSAGE" TEXT,
    "METADATA" JSONB,
    "SENT_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "NOTIFICATION_LOGS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex (idempotent)
CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_TENANT_ID_idx" ON "NOTIFICATION_LOGS"("TENANT_ID");

CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_TENANT_ID_SENT_AT_idx" ON "NOTIFICATION_LOGS"("TENANT_ID", "SENT_AT");

CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_RECIPIENT_EMAIL_idx" ON "NOTIFICATION_LOGS"("RECIPIENT_EMAIL");

CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_TYPE_idx" ON "NOTIFICATION_LOGS"("TYPE");

CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_STATUS_idx" ON "NOTIFICATION_LOGS"("STATUS");

CREATE INDEX IF NOT EXISTS "NOTIFICATION_LOGS_SENT_AT_idx" ON "NOTIFICATION_LOGS"("SENT_AT");
